# Generated by Django 4.1.4 on 2022-12-11 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('tags', models.CharField(max_length=50)),
                ('url', models.URLField(max_length=30)),
                ('image', models.ImageField(upload_to='portfolio/images')),
            ],
        ),
    ]
